# Generated by Django 4.1.2 on 2022-11-13 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_dt', models.CharField(max_length=40)),
                ('apellido_dt', models.CharField(max_length=40)),
                ('pais_dt', models.CharField(max_length=40)),
                ('seleccion_representada', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Jugadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres_jugador', models.CharField(max_length=40)),
                ('apellidos_jugador', models.CharField(max_length=40)),
                ('numero_camiseta', models.IntegerField()),
                ('pais_jugador', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='selecciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=10)),
                ('num_jugadores_convocados', models.IntegerField()),
                ('capitan', models.CharField(max_length=40)),
            ],
        ),
    ]
