# Generated by Django 4.1.2 on 2022-11-14 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmundial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='lesionados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_jug_les', models.CharField(max_length=40)),
                ('ape_jug_les', models.CharField(max_length=40)),
            ],
        ),
    ]
