# Generated by Django 4.1.2 on 2022-11-21 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmundial', '0002_lesionados'),
    ]

    operations = [
        migrations.AddField(
            model_name='selecciones',
            name='nombre_seleccion',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
